### ISSUE TITLE
command fails on Mac

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [ObjectIsAdvantag/guestissuer#1]
env \r error on Mac / node v7.9.0

**Comment by ObjectIsAdvantag** [comment]
manually removed the CR on the first line of guestissuer for better Mac compatibility, 
and republished as v0.6.1

tested ok on my Mac and windows machine

waiting for jfield44 feedback on this, did it fix ?

**Comment by jfield44** [comment]
It works now. Thanks @ObjectIsAdvantag

**Comment by ObjectIsAdvantag** [comment]
cool, thanks for raising the issue, I learnt more about npm internals on the way ;-)
